### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by Ghosts** [Pinjasaur/whenisgucci#130]
## Summary
The lack of sanitization of the event name field in the creation of events opens up the possibility for a malicious actor to hijack & inject arbitrary page code by specially formatted event titles.

### Proof of concept
https://whenisgucci.com/event/vQBx/respond?utm_source=gucci4me

The example above highlights creating an event with the name:
`</script><script>alert('h4x0rd')</script>`

In which the first `</script>` tag ends the enclosing script, and a new `<script></script>` block is created, in which an alert is writen to the DOM. This could easily be substituted with AJAX calls, route hijacking, cookie stealing, or more.

**Comment by Pinjasaur** [comment]
Ultimately this is due to browsers looking for the string "</script>" literally to close an inline `<script>` tag. This is what is happening in this case.

Since `<script>`s do not handle HTML entities (e.g. `&lt;`), all `<` must be replaced with `\u003c`.

The following Stack Overflow goes over an implementation that should work since we're utilizing Nunjucks for templating. https://stackoverflow.com/questions/46426306/how-to-safely-render-json-into-an-inline-script-using-nunjucks
